apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taixiu-backend-rollout
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Hung0codon/ArgoCD-Project.git
    targetRevision: main
    path: gitops/taixiu/backend-rollout/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
