apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: taixiu-backend-success-rate
  namespace: demo
spec:
  metrics:
  - name: error-rate
    interval: 30s
    count: 4
    successCondition: result[0] < 0.05
    failureLimit: 0
    provider:
      prometheus:
        address: http://prometheus-service.monitoring.svc.cluster.local:9090
        query: |
          (sum(rate(http_requests_total{status=~"5..", kubernetes_namespace="demo", app="taixiu-backend"}[2m])) or vector(0))
          /
          (sum(rate(http_requests_total{kubernetes_namespace="demo", app="taixiu-backend"}[2m])) or vector(1))
