apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: taixiu-backend
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taixiu-backend
  template:
    metadata:
      labels:
        app: taixiu-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: taixiu-backend
        image: taixiu-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: { duration: 10s }
      - analysis:
          templates:
          - templateName: taixiu-backend-success-rate
      - setWeight: 50
      - pause: { duration: 10s }
      - setWeight: 100
